version: '2'
services:
  mongo:
    image: mongo
    ports:
     - "27017"
  redis:
    image: redis
    ports:
     - "6379"

  cwmp:
    image: fgiana/genieacs
    ports:
     - "7547:7547"
    depends_on:
     - redis
     - mongo
    #volumes:
    # - /root/scenario/config.json:/opt/genieacs/config/config.json:ro
    links:
     - mongo:mongodb_host
     - redis:redis_host
    command: /opt/genieacs/bin/genieacs-cwmp

  nbi:
    image: fgiana/genieacs
    ports:
     - "7557:7547"
    depends_on:
     - redis
     - mongo
    #volumes:
    # - /root/scenario/config.json:/opt/genieacs/config/config.json:ro
    links:
     - mongo:mongodb_host
     - redis:redis_host
    command: /opt/genieacs/bin/genieacs-nbi

  fs:
    image: fgiana/genieacs
    ports:
     - "7567:7547"
    depends_on:
     - redis
     - mongo
    #volumes:
    # - /root/scenario/config.json:/opt/genieacs/config/config.json:ro
    links:
     - mongo:mongodb_host
     - redis:redis_host
    command: /opt/genieacs/bin/genieacs-fs

  gui:
    image: fgiana/genieacs_gui
    ports:
     - "3000:3000"
    depends_on:
     - redis
     - mongo
    depends_on:
     - nbi
    #volumes:
    # - /root/scenario/config.json:/opt/genieacs/config/config.json:ro
    links:
     - nbi:genieacs_api_host    